name: Reusable workflow 

on:
  workflow_call:
    outputs:
      application-url:
        value: ${{ jobs.resuse-deploy.outputs.APP_INGRESS_HOST }}
    inputs:
      mongo-uri:
        required: true 
        type: string
      kubectl-version:
        required: false
        default: v1.26.0
        type: string
        description: Kubectl version to use
      k8s-manifest-dir:
        required: true
        type: string
        description: 'Directory containing k8s manifests'
        default: kubernetes/
      environment:
        required: true
        type: string
        description: Environment to deploy to
        default: development
    secrets:
      k8s-config:
        required: true
      mongodb-password:
        required: true

jobs:
  resuse-deploy:
    environment:
        name: ${{ inputs.environment }}
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      
    outputs:
        APP_INGRESS_HOST: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4


      - name: Install kubectl cli
        uses: azure/setup-kubectl@v4
        with:
          version: '${{ inputs.kubectl-version }}'

      - name: set kubeconfig file
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-config }}

      - name: Verify Kubernetes cluster
        run: |
           kubectl cluster-info
           kubectl get nodes 

      - name: Save nginx ingress controller ip as GITHUB Env Variable
        run: |
          echo "INGRESS_IP=$(kubectl get svc -n ingress-nginx ingress-nginx-controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Replace token in Manifest file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '${'
          tokenSuffix: '}'
          files: '["${{ inputs.k8s-manifest-dir}}*.yaml"]'
        env:
            NAMESPACE: ${{ vars.NAMESPACE}}
            REPLICAS: ${{ vars.REPLICAS}}
            K8S_IMAGE: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: check files
        run: |
           cat ${{ inputs.k8s-manifest-dir}}*.yaml

      - name: Create MongoDb Secrets
        run: |
            kubectl -n ${{ vars.NAMESPACE}} create secret generic mongo-creds \
            --from-literal=MONGO_URI=${{inputs.mongo-uri}} \
            --from-literal=MONGO_USERNAME=${{vars.MONGO_USERNAME}} \
            --from-literal=MONGO_PASSWORD=${{secrets.mongodb-password}} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -

      - name: Deploy to dev Env
        run: |
            kubectl apply -f ${{ inputs.k8s-manifest-dir}}

    # after creating all the above steps , i can see in my cluster all the pods are running and to access the application 
    # kubectl get ing -n develpment , it will give the hostname and ip address of the application
    # i can access the application using the hostname and ip address

      - name: Set app ingress host URL
        id: set-ingress-host-address
        run: |
            echo "APP_INGRESS_HOST=$(kubectl get ing -n ${{ vars.NAMESPACE}} -o jsonpath='{.items[0].spec.tls[0].hosts[0]}')" >> $GITHUB_OUTPUT

 